authors:
  jantrueno:
    name: JanTrueno
    description: PortMaster Crew Member
    avatar: https://avatars.githubusercontent.com/u/159560609?v=4
    url: https://github.com/JanTrueno
  kloptops:
    name: Kloptops
    description: PortMaster Crew Member
    avatar: https://avatars.githubusercontent.com/u/4617076?v=4
    url: https://github.com/kloptops
  bamboozler:
    name: Bamboozler
    description: PortMaster Crew Member
    avatar: https://avatars.githubusercontent.com/u/1930031?v=4
    url: https://github.com/christopher-roelofs
